Problem: (fix #196) current goreleaser config may build binaries without ledger support
crypto-com/chain-main pull request #214
Opened 2020-10-26 03:51 UTC by linfeng-crypto

solution: use docker to cross-compile the binary with `cgo` enabled

2020-10-26 06:41 UTC, yihuang commented on .goreleaser.yml
> +  - id: "chain-maind-darwin"
is this intended?

2020-10-26 07:18 UTC, linfeng-crypto commented on .goreleaser.yml
> +  - id: "chain-maind-darwin"
I tried to use the same id, failed

2020-10-28 01:28 UTC, leejw51crypto approved these changes
lgtm

2020-10-29 02:14 UTC, tomtau reviewed
looks all right -- I don't have much experience with Go Releaser, so may wait for @allthatjazzleo or @calvinaco comments and merge it by today

2020-10-29 03:43 UTC, allthatjazzleo commented
@tomtau I will try to release in fork repo

2020-10-29 04:08 UTC, allthatjazzleo commented on Makefile
> +		troian/golang-cross:${GOLANG_CROSS_VERSION} \
I got this error
```
docker: Error response from daemon: manifest for troian/golang-cross:1.13.15 not found: manifest unknown: manifest unknown.
```

2020-10-29 04:13 UTC, tomtau commented on Makefile
> +		troian/golang-cross:${GOLANG_CROSS_VERSION} \
@linfeng-crypto

2020-10-29 05:54 UTC, allthatjazzleo commented on .github/workflows/goreleaser.yml
> +          run: make release-dry-run
```suggestion
        run: make release-dry-run
```
I got
```
Invalid workflow file
You have an error in your yaml syntax on line 15
```
should be related to indentation 
same for below

2020-10-29 07:54 UTC, allthatjazzleo commented on .goreleaser.yml
> +  - darwin
```suggestion
  - chain-maind-darwin
  - chain-maind-windows
  - chain-maind-linux
```
should match id

2020-10-29 07:55 UTC, allthatjazzleo requested changes

2020-10-29 07:55 UTC, allthatjazzleo commented on .github/workflows/goreleaser.yml
> +         run: make release-dry-run
the indent of `run` is still not aligned with `name`

2020-10-29 08:14 UTC, allthatjazzleo commented on Makefile
> +		-it \
```suggestion
```
github actions cannot run with `-it`
with error
`the input device is not a TTY`

2020-10-30 01:43 UTC, tomtau approved these changes

2020-10-30 04:23 UTC, allthatjazzleo approved these changes

2020-10-30 05:32 UTC, merged