Problem: (fix #305) pystarport missing optional pubkey in config
crypto-com/chain-main pull request #357
Opened 2021-01-16 08:50 UTC by allthatjazzleo

Solution: add option for pubkey in pystarport

2021-01-16 13:59 UTC, yihuang commented on pystarport/pystarport/cosmoscli.py
> +            **{k: v for k, v in options.items() if v is not None},
```suggestion
            pubkey=pubkey,
```

It already filter out `None` values.

2021-01-16 14:05 UTC, yihuang approved these changes
LGTM, small suggestions.

2021-01-18 01:19 UTC, tomtau requested changes
https://github.com/crypto-com/chain-main/pull/357/checks?check_run_id=1716264450#step:5:49

2021-01-18 01:19 UTC, tomtau commented on pystarport/pystarport/cosmoscli.py
> +        options = dict(
not needed?

2021-01-19 03:52 UTC, allthatjazzleo commented on pystarport/pystarport/cosmoscli.py
> +        options = dict(
fixed

2021-01-19 05:31 UTC, tomtau approved these changes

2021-01-19 05:31 UTC, merged